---
cozy_state: present
cozystack_couchdb_address: localhost:5984
cozystack_couchdb_nodename: couchdb@localhost
cozystack_couchdb_admin_user: admin
cozystack_couchdb_admin_password: admin
cozystack_couchdb_cozy_user: cozy
cozystack_couchdb_cozy_password: cosy
cozystack_cozy_address: cozy
cozystack_cozy_password: cozy
cozystack_address: 127.0.0.1
cozystack_port: "8080"
cozystack_admin_address: 127.0.0.1
cozystack_admin_port: "6060"
